In [1]:
import numpy as np
import sys
import os

In [2]:
base_dir = os.path.dirname(os.getcwd())
sys.path.append(base_dir)

In [7]:
from src.metrics.energy_base_metrics import Precision_energy_based, Recall_energy_based, F1_energy_based, NEP, MAE

In [4]:
y_pred = np.random.rand(1000,9)
y_target = np.random.rand(1000, 9)

In [6]:
Precision_energy_based(y_pred, y_target)

array([0.66609007, 0.65480773, 0.660839  , 0.65372757, 0.66353173,
       0.64728217, 0.66924729, 0.64961754, 0.66794931])

In [ ]:
Recall_energy_based(y_pred, y_target)

array([1.51426375, 1.49276898, 1.44960097, 1.43429202, 1.47827861,
       1.47435517, 1.51920889, 1.45246513, 1.51485879])

In [ ]:
F1_energy_based(y_pred, y_target)

array([0.6621203 , 0.67558829, 0.68363173, 0.67822952, 0.67264079,
       0.67750257, 0.64965992, 0.67039237, 0.655372  ])

In [8]:
NEP(y_pred, y_target)

array([0.66304139, 0.68398812, 0.66536778, 0.68842813, 0.67643639,
       0.68928733, 0.66881759, 0.69225461, 0.6653213 ])

In [9]:
MAE(y_pred, y_target)

array([0.32895633, 0.33781085, 0.32898361, 0.33788929, 0.3387175 ,
       0.33070495, 0.3379857 , 0.34219025, 0.33126742])

In [ ]:
y_pred_fail = np.random.rand(1000, 8)
Precision_energy_bases(y_pred_fail, y_target)

AssertionError: number of appliances not match

In [ ]:
y_pred_fail = np.random.rand(1001, 9)
Precision_energy_bases(y_pred_fail, y_target)

AssertionError: samples number not match